steps:
# Uses the ubuntu build step:
# to run a shell script; and
# set env variables for its execution
- name: 'ubuntu'
  entrypoint: bash
  args:
  - ls -a /workspace/.git
    # sed -i -e s/#CONTAINER_NAME/_CONTAINER_NAME/g vars.tfvars
      # sed -i -e s/#CONTAINER_TAG/_CONTAINER_TAG/g vars.tfvars
      # sed -i -e s/#PROJECT/_PROJECT/g vars.tfvars
      # sed -i -e s/#REGION/_REGION/g vars.tfvars
      # sed -i -e s/#TENANT/_TENANT/g vars.tfvars
      # sed -i -e s/#BUCKET/_BUCKET/g backend.config
      # sed -i -e s/#TENANT/_TENANT/g backend.config
      # cat vars.tfvars
      # cat backend.config
# - id: 'tf init'
#   name: 'hashicorp/terraform:0.15.5'
#   entrypoint: 'sh'
#   args:
#   - '-c'
#   - 'terraform init --backend-config=backend.config'
# - id: 'tf plan'
#   name: 'hashicorp/terraform:0.15.5'
#   entrypoint: 'sh'
#   args:
#   - '-c'
#   - 'terraform plan --var-file=vars.tfvars'
substitutions:
  _BUCKET: 'arri-tenants-state'
  _CONTAINER_NAME: 'hello-app'
  _CONTAINER_TAG: '1.0'
  _PROJECT: 'arri-primary'
  _REGION: 'us-east4'
  _TENANT: 'bojangles'
#options:
# logging: CLOUD_LOGGING_ONLY

